INSERT INTO movie_theater.movie (title,director,rating,price)
VALUES
('The Shawshank Redemption','Frank Darabont','9.2','10'),
('The Godfather','Francis Ford Coppola','9.2','10'),
('The Godfather: Part II','Francis Ford Coppola','9','10'),
('The Dark Knight','Christopher Nolan','9','10'),
('12 Angry Men','Sidney Lumet','8.9','10'),
('Schindler''s List','Steven Spielberg','8.9','10'),
('The Lord of the Rings: The Return of the King','Peter Jackson','8.9','10'),
('Pulp Fiction','Quentin Tarantino','8.9','10'),
('The Good, the Bad and the Ugly','Sergio Leone','8.8','10'),
('Fight Clu','David Fincher','8.8','10'),
('The Lord of the Rings: The Fellowship of the Ring','Peter Jackson','8.8','10'),
('Forrest Gump','Robert Zemeckis','8.7','10'),
('Star Wars: Episode V - The Empire Strikes Back','Irvin Kershner','8.7','10'),
('Inception','Christopher Nolan','8.7','10'),
('The Lord of the Rings: The Two Towers','Peter Jackson','8.7','10'),
('One Flew Over the Cuckoos Nest','Milos Forman','8.7','10'),
('Goodfellas','Martin Scorsese','8.7','10'),
('The Matrix','Lana Wachowski','8.6','10'),
('Seven Samurai','Akira Kurosawa','8.6','10'),
('City of God','Fernando Meirelles','8.6','10'),
('Se7en','David Fincher','8.6','10'),
('Star Wars: Episode IV - A New Hope','George Lucas','8.6','10'),
('The Silence of the Lambs','Jonathan Demme','8.6','10'),
('It''s a Wonderful Life','Frank Capra','8.6','10'),
('Life Is Beautiful','Roberto Benigni','8.6','10'),
('The Usual Suspects','Bryan Singer','8.5','10'),
('Spirited Away','Hayao Miyazaki','8.5','10'),
('Saving Private Ryan','Steven Spielberg','8.5','10'),
('Leon: The Professional','Luc Besson','8.5','10'),
('The Green Mile','Frank Darabont','8.5','10'),
('Interstellar','Christopher Nolan','8.5','10'),
('Psycho','Alfred Hitchcock','8.5','10'),
('American History X','Tony Kaye','8.5','10'),
('City Lights','Charles Chaplin','8.5','12'),
('Once Upon a Time in the West','Sergio Leone','8.5','12'),
('Casablanca','Michael Curtiz','8.5','12'),
('Modern Times','Charles Chaplin','8.5','12'),
('The Intouchables','Olivier Nakache','8.5','12'),
('The Pianist','Roman Polanski','8.5','12'),
('The Departed','Martin Scorsese','8.5','12'),
('Terminator 2: Judgment Day','James Cameron','8.5','12'),
('Back to the Future','Robert Zemeckis','8.5','12'),
('Whiplash','Damien Chazelle','8.5','12'),
('Rear Window','Alfred Hitchcock','8.5','12'),
('Raiders of the Lost Ark','Steven Spielberg','8.5','12'),
('Gladiator','Ridley Scott','8.5','12'),
('The Lion King','Roger Allers','8.5','12'),
('The Prestige','Christopher Nolan','8.5','12'),
('Apocalypse Now','Francis Ford Coppola','8.4','12'),
('Memento','Christopher Nolan','8.4','12');